version: '3'

services:
  backend:
    build: ./backend
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://your_domain.com/api

  redis:
    image: redis:latest

  celery:
    build: ./backend
    command: celery -A project worker -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  celery-beat:
    build: ./backend
    command: celery -A project beat -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - celery

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend